# Generated by Django 6.0.3 on 2026-03-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('file_name', models.CharField(default='', max_length=255)),
                ('chart_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
